version: '3'
services:
  prometheus:
    container_name: cert-manager-prometheus
    image: prom/prometheus:v2.5.0
    ports:
      - '9090:9090'
    volumes:
      - ./prometheus/:/etc/prometheus/
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
